### ISSUE TITLE
List of things to be done before first stable release

### ISSUE THREAD

**Issue by Albert221** [Albert221/FromSelect#2]
- [ ] Frontend
  - [x] Login page
  - [ ] New database popup ([PE](https://en.wikipedia.org/wiki/Progressive_enhancement); for those w/o JS)
  - [ ] New database view
  - [x] Databases' list view
  - [ ] Blank tables' list view (ig CTA new table)
  - [x] Tables' list view
  - [x] Table's data view (which would be just result view, i.e. for SQL query results)
  - [ ] Table's structure view
  - [ ] Table's operations view
  - [ ] New row view
  - [ ] New row popup (*probably*; for those w/o JS)
  - [ ] Delete row confirmation popup
  - [ ] **UX at very high level** #6
- [x] SQL code highlighting
- [ ] SQL query popup triggerred by key binding #1 
- [ ] Internationalization
  - [ ] Choose (thus maybe implement) language system #3
  - [ ] English translation
  - [ ] Polish translation
- [ ] **Presets** for tables and columns

And somehow related (edited by Sobak 12/30/2016):
- [ ] README
- [ ] Logo&favicon
- [ ] Determine list of desired features

**Comment by Sobak** [comment]
Suspended by separate issues
